name: AudioVisual Management Worldwide
favicon: null
layout_spectrum: 0.44894
typography_spectrum: 0.22027
title: 'Your A/V Partner - Anywhere, Anytime, Anything.  '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#131c3f'
    - '#db4f2b'
    - '#e99579'
    - '#535353'
  brandStrength: 1
  lightness: 0
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
