name: avmw
favicon: null
layout_spectrum: 0.9311590592842549
typography_spectrum: 0.13814869243651628
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4519704063422978
  lightness: 0.8010321776382625
  saturation: 0.26298165787011385
  rhythmicContrast: 0.47363164625130594
purpose: []
